export const AJOUTER_PRODUIT = "AJOUTER_PRODUIT";
export const AJOUTER_PRODUIT_PRDODETAIL = "AJOUTER_PRODUIT_PRDODETAIL";
export const DELETE_PRODUIT = "DELETE_PRODUIT";
export const ADD_PRODUIT = "ADD_PRODUIT";
export const MINUS_PRODUIT = "MINUS_PRODUIT";
