export const FETCH_CATEGORIE = "FETCH_CATEGORIE";
export const FETCH_CATEGORIE_REQUEST = "FETCH_CATEGORIE_REQUEST";
export const FETCH_CATEGORIE_SUCCESS = "FETCH_CATEGORIE_SUCCESS";
export const FETCH_CATEGORIE_ERROR = "FETCH_CATEGORIE_ERROR";
export const DELETE_CATEGORIE = "DELETE_CATEGORIE";
