export const FETCH_TYPESBOUTIQUE_REQUEST = "FETCH_TYPESBOUTIQUE_REQUEST";
export const FETCH_TYPESBOUTIQUE_SUCCESS = "FETCH_TYPESBOUTIQUE_SUCCESS";
export const FETCH_TYPESBOUTIQUE_FAILURE = "FETCH_TYPESBOUTIQUE_FAILURE";
